import { colors, components, layout, spacing, tokens, typography } from "./tokens";

type TokenVarMap = Record<`--${string}`, string | number>;

const tokenVars: TokenVarMap = {
  "--font-sans": typography.fontFamily,
  "--font-mono": tokens.typography.families.mono,
  "--color-bg-preview": colors.bg.preview,
  "--color-bg-page": colors.bg.page,
  "--color-bg-page-alt": colors.bg.pageAlt,
  "--color-bg-panel": colors.bg.panel,
  "--color-bg-panel-soft": colors.bg.panelSoft,
  "--color-bg-panel-wash": colors.bg.panelWash,
  "--color-bg-panel-raised": colors.bg.panelRaised,
  "--color-bg-chip": colors.bg.chip,
  "--color-text-primary": colors.text.primary,
  "--color-text-secondary": colors.text.secondary,
  "--color-text-tertiary": colors.text.tertiary,
  "--color-text-muted": colors.text.muted,
  "--color-text-subtle": colors.text.subtle,
  "--color-border-subtle": colors.border.subtle,
  "--color-border-standard": colors.border.standard,
  "--color-border-strong": colors.border.strong,
  "--color-border-emphasis": colors.border.emphasis,
  "--color-accent-primary": colors.accent.primary,
  "--color-accent-secondary": colors.accent.secondary,
  "--color-accent-warning": colors.accent.warning,
  "--color-accent-risk": colors.accent.risk,
  "--color-accent-stable": colors.accent.stable,
  "--shadow-subtle": tokens.shadows.subtle,
  "--shadow-elevated": tokens.shadows.elevated,
  "--color-signal-coordination": colors.signal.coordination,
  "--color-signal-allocation": colors.signal.allocation,
  "--color-signal-infrastructure": colors.signal.infrastructure,
  "--color-signal-markets": colors.signal.markets,
  "--color-category-strategy": colors.category.strategy,
  "--color-category-pressure": colors.category.pressure,
  "--color-category-risk": colors.category.risk,
  "--color-category-infrastructure": colors.category.infrastructure,
  "--color-category-market": colors.category.market,
  "--color-category-evidence": colors.category.evidence,
  "--space-micro": spacing.micro,
  "--space-xs": spacing.xs,
  "--space-sm": spacing.sm,
  "--space-md": spacing.md,
  "--space-lg": spacing.lg,
  "--space-xl": spacing.xl,
  "--space-xxl": spacing.xxl,
  "--radius-sm": components.radius.sm,
  "--radius-md": components.radius.md,
  "--radius-lg": components.radius.lg,
  "--radius-xl": components.radius.xl,
  "--radius-pill": components.radius.pill,
  "--panel-padding": components.panel.padding,
  "--panel-padding-compact": components.panel.compactPadding,
  "--panel-inset-highlight": components.panel.insetHighlight,
  "--layout-page-width-portrait": layout.page.portraitWidth,
  "--layout-page-height-portrait": layout.page.portraitHeight,
  "--layout-page-width-landscape": layout.page.landscapeWidth,
  "--layout-page-height-landscape": layout.page.landscapeHeight,
  "--layout-page-padding-top": layout.page.paddingTop,
  "--layout-page-padding-right": layout.page.paddingRight,
  "--layout-page-padding-bottom": layout.page.paddingBottom,
  "--layout-page-padding-left": layout.page.paddingLeft,
  "--layout-page-footer-height": layout.page.footerHeight,
  "--layout-grid-gutter": layout.grid.gutter,
  "--layout-grid-gutter-compact": layout.grid.compactGutter,
  "--layout-board-padding-top": layout.board.pagePaddingTop,
  "--layout-board-padding-right": layout.board.pagePaddingRight,
  "--layout-board-padding-bottom": layout.board.pagePaddingBottom,
  "--layout-board-padding-left": layout.board.pagePaddingLeft,
  "--type-title-size": typography.title.fontSize,
  "--type-title-line": typography.title.lineHeight,
  "--type-title-track": typography.title.letterSpacing,
  "--type-title-weight": typography.title.fontWeight,
  "--type-heading-size": typography.heading.fontSize,
  "--type-heading-line": typography.heading.lineHeight,
  "--type-heading-track": typography.heading.letterSpacing,
  "--type-heading-weight": typography.heading.fontWeight,
  "--type-subheading-size": typography.subheading.fontSize,
  "--type-subheading-line": typography.subheading.lineHeight,
  "--type-subheading-track": typography.subheading.letterSpacing,
  "--type-subheading-weight": typography.subheading.fontWeight,
  "--type-body-size": typography.body.fontSize,
  "--type-body-line": typography.body.lineHeight,
  "--type-body-weight": typography.body.fontWeight,
  "--type-body-compact-size": typography.bodyCompact.fontSize,
  "--type-body-compact-line": typography.bodyCompact.lineHeight,
  "--type-body-compact-weight": typography.bodyCompact.fontWeight,
  "--type-meta-size": typography.meta.fontSize,
  "--type-meta-line": typography.meta.lineHeight,
  "--type-meta-track": typography.meta.letterSpacing,
  "--type-meta-weight": typography.meta.fontWeight,
  "--type-label-size": typography.label.fontSize,
  "--type-label-line": typography.label.lineHeight,
  "--type-label-track": typography.label.letterSpacing,
  "--type-label-weight": typography.label.fontWeight,
  "--type-signal-size": typography.signalValue.fontSize,
  "--type-signal-line": typography.signalValue.lineHeight,
  "--type-signal-weight": typography.signalValue.fontWeight,
};

export const exportTokenCssText = `
.export-root,
.export-document,
.export-preview-shell {
${Object.entries(tokenVars)
  .map(([name, value]) => `  ${name}: ${value};`)
  .join("\n")}
}
`;
